# See https://pre-commit.com for more information
---
repos:
    # General

    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files
          - id: check-shebang-scripts-are-executable
          - id: check-json
          - id: check-yaml
    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: 3.1.2
      hooks:
          - id: editorconfig-checker
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.23.1
      hooks:
          - id: gitleaks
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint

    # Language specific

    - repo: local
      hooks:
          - id: npm-format
            name: Prettier format
            entry: npm run format
            language: system
            pass_filenames: false
